
### Theme ###
remote_theme  : chrisrhymes/bulma-clean-theme
theme_color   : '#022343'


### Site settings ###
title   : JES
tagline   : PhD Student
lang    : en
email   : josesolorzano689@gmail.com
description : 
baseurl   : "" # the subpath of your site, e.g. /blog
url   : "https://jsolorzano734.github.io"
open_new_tab  : true  

# Site Social
twitter_username : josesolorzano73
github_username  : jsolorzano734

# Site Logos
logo    : "assets/images/site_images/logoJoseJ.png"
favicon : assets/images/site_images/logoJoseJ.png


# Author Info
author:
  name      : "Jose E. Solorzano"
  avatar    : "assets/images/site_images/Jose_grayBackground.jpg"
  intro     : "I am passionate about plants and fungi"
  bio       : "Plant Pathologist"
  blurb     : "PhD Student and Research Assistant"
  location  : "Saint Paul, MN"
  email     : josesolorzano689@gmail.com
  github    :
  linkedin  : josé-e-solórzano-720a25168
  twitter   : josesolorzano73
  facebook  :
  instagram :
  youtube   : 


# Custom Footer
custom_footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/josesolorzano73"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/josé-e-solórzano-720a25168"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram-square"
      url: "https://www.instagram.com/jsolorzano734/"


### Analytics ###
google_analytics: G-VGG7Q8FP0S



# Build settings
markdown: kramdown
#theme: minima

plugins:
  - jekyll-feed
  
include:
  - _pages

permalink: pretty

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
