## Theme
remote_theme  : chrisrhymes/bulma-clean-theme
theme_color   : '#022343'


## Site settings
title   : Jose E. Solorzano
tagline   : 
lang    : en
email   : ortiz432@umn.edu
description : 
baseurl   : "" # the subpath of your site, e.g. /blog
url   : "https://jsolorzano734.github.io"
open_new_tab  : true  

# Social media
twitter_username : josesolorzano734
github_username  : jsolorzano734

# Site Logos
logo    : ""
favicon : 


# Author Info
author:
  name      : "Jose E. Solorzano"
  avatar    : ""
  intro     : ""
  bio       : "Data Scientist"
  blurb     : ""
  location  : "Saint Paul, MN"
  email     : ortiz432@umn.edu
  github    : jsolorzano734
  linkedin  : Jose E Solorzano
  twitter   : josesolorzano734
  facebook  :
  instagram : jsolorzano734
  youtube   : jose E Solorzano


## Footer
# footer_menu: my_footer

# Custom Footer
custom_footer:
  links:
    - label: "Twitter"
      icon: ""
      url: "https://twitter.com/josesolorzano734"
    - label: "LinkedIn"
      icon: ""
      url: "https://www.linkedin.com/in/jos%C3%A9-e-sol%C3%B3rzano-720a25168/"
    - label: "Instagram"
      icon: ""
      url: "https://wwww.instagram.com/jsolorzano734"


## Analytics
google_analytics: UA-320062591
# Build settings
 markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/